#ifndef EXACT_COVER_VECTOR_H
#define EXACT_COVER_VECTOR_H

#include "vector_def.h"






MAKE_VECTOR(Int, SIMPLE);
MAKE_VECTOR(Char, SIMPLE);
MAKE_VECTOR(Double, SIMPLE);
MAKE_VECTOR(Bool, SIMPLE);
MAKE_VECTOR(Complex, SIMPLE)


MAKE_VECTOR(VectorInt, STRUCT);

MAKE_VECTOR(VectorVectorInt, STRUCT);

MAKE_VECTOR(VectorBool, STRUCT)

MAKE_VECTOR(GeneralType, STRUCT)

MAKE_VECTOR(VectorGeneralType, STRUCT)



#endif //EXACT_COVER_VECTOR_H
